package com.prairiefarms.billing.document.xlsx.workbook;

import org.apache.poi.ss.usermodel.*;
import org.apache.poi.xssf.usermodel.*;

import java.util.HashMap;

public class CellStyleMap {

    public HashMap<String, XSSFCellStyle> styles = new HashMap<>();

    private static class SingletonHelper {
        private static final CellStyleMap INSTANCE = new CellStyleMap();
    }

    CellStyleMap() {
    }

    public static CellStyleMap getInstance() {
        return SingletonHelper.INSTANCE;
    }

    public XSSFCellStyle getStyle(String identifier) {
        return (styles.get(identifier));
    }

    public void init(XSSFWorkbook xssfWorkbook) {
        XSSFFont PROPORTIONAL_FONT_12_POINT_BOLD = xssfWorkbook.createFont();
        PROPORTIONAL_FONT_12_POINT_BOLD.setFontName(WorkbookEnvironment.PROPORTIONAL_FONT_NAME);
        PROPORTIONAL_FONT_12_POINT_BOLD.setFontHeightInPoints(WorkbookEnvironment.FONT_SIZE_12_POINT);
        PROPORTIONAL_FONT_12_POINT_BOLD.setBold(true);

        XSSFCellStyle PROPORTIONAL_FONT_12_POINT_BOLD_ALIGN_CENTER = xssfWorkbook.createCellStyle();
        PROPORTIONAL_FONT_12_POINT_BOLD_ALIGN_CENTER.setFont(PROPORTIONAL_FONT_12_POINT_BOLD);
        PROPORTIONAL_FONT_12_POINT_BOLD_ALIGN_CENTER.setVerticalAlignment(VerticalAlignment.CENTER);
        PROPORTIONAL_FONT_12_POINT_BOLD_ALIGN_CENTER.setAlignment(HorizontalAlignment.CENTER);
        styles.put("PROPORTIONAL_FONT_12_POINT_BOLD_ALIGN_CENTER", PROPORTIONAL_FONT_12_POINT_BOLD_ALIGN_CENTER);

        XSSFCellStyle PROPORTIONAL_FONT_12_POINT_BOLD_ALIGN_RIGHT = xssfWorkbook.createCellStyle();
        PROPORTIONAL_FONT_12_POINT_BOLD_ALIGN_RIGHT.setFont(PROPORTIONAL_FONT_12_POINT_BOLD);
        PROPORTIONAL_FONT_12_POINT_BOLD_ALIGN_RIGHT.setVerticalAlignment(VerticalAlignment.CENTER);
        PROPORTIONAL_FONT_12_POINT_BOLD_ALIGN_RIGHT.setAlignment(HorizontalAlignment.RIGHT);
        styles.put("PROPORTIONAL_FONT_12_POINT_BOLD_ALIGN_RIGHT", PROPORTIONAL_FONT_12_POINT_BOLD_ALIGN_RIGHT);

        XSSFCellStyle PROPORTIONAL_FONT_12_POINT_BOLD_ALIGN_RIGHT_BLUE = xssfWorkbook.createCellStyle();
        PROPORTIONAL_FONT_12_POINT_BOLD_ALIGN_RIGHT_BLUE.cloneStyleFrom(PROPORTIONAL_FONT_12_POINT_BOLD_ALIGN_CENTER);
        PROPORTIONAL_FONT_12_POINT_BOLD_ALIGN_RIGHT_BLUE.setAlignment(HorizontalAlignment.RIGHT);
        PROPORTIONAL_FONT_12_POINT_BOLD_ALIGN_RIGHT_BLUE.setFillForegroundColor(WorkbookEnvironment.CELL_BACKGROUND_CUSTOM_BLUE);
        PROPORTIONAL_FONT_12_POINT_BOLD_ALIGN_RIGHT_BLUE.setFillPattern(FillPatternType.SOLID_FOREGROUND);
        styles.put("PROPORTIONAL_FONT_12_POINT_BOLD_ALIGN_RIGHT_BLUE", PROPORTIONAL_FONT_12_POINT_BOLD_ALIGN_RIGHT_BLUE);

        XSSFFont PROPORTIONAL_FONT_10_POINT_BOLD = xssfWorkbook.createFont();
        PROPORTIONAL_FONT_10_POINT_BOLD.setFontName(WorkbookEnvironment.PROPORTIONAL_FONT_NAME);
        PROPORTIONAL_FONT_10_POINT_BOLD.setFontHeightInPoints(WorkbookEnvironment.FONT_SIZE_10_POINT);
        PROPORTIONAL_FONT_10_POINT_BOLD.setBold(true);

        XSSFCellStyle PROPORTIONAL_FONT_10_POINT_BOLD_ALIGN_LEFT_BLUE = xssfWorkbook.createCellStyle();
        PROPORTIONAL_FONT_10_POINT_BOLD_ALIGN_LEFT_BLUE.setFont(PROPORTIONAL_FONT_10_POINT_BOLD);
        PROPORTIONAL_FONT_10_POINT_BOLD_ALIGN_LEFT_BLUE.setVerticalAlignment(VerticalAlignment.CENTER);
        PROPORTIONAL_FONT_10_POINT_BOLD_ALIGN_LEFT_BLUE.setAlignment(HorizontalAlignment.LEFT);
        PROPORTIONAL_FONT_10_POINT_BOLD_ALIGN_LEFT_BLUE.setFillForegroundColor(WorkbookEnvironment.CELL_BACKGROUND_CUSTOM_BLUE);
        PROPORTIONAL_FONT_10_POINT_BOLD_ALIGN_LEFT_BLUE.setFillPattern(FillPatternType.SOLID_FOREGROUND);
        styles.put("PROPORTIONAL_FONT_10_POINT_BOLD_ALIGN_LEFT_BLUE", PROPORTIONAL_FONT_10_POINT_BOLD_ALIGN_LEFT_BLUE);

        XSSFCellStyle PROPORTIONAL_FONT_10_POINT_BOLD_ALIGN_RIGHT_BLUE = xssfWorkbook.createCellStyle();
        PROPORTIONAL_FONT_10_POINT_BOLD_ALIGN_RIGHT_BLUE.cloneStyleFrom(PROPORTIONAL_FONT_10_POINT_BOLD_ALIGN_LEFT_BLUE);
        PROPORTIONAL_FONT_10_POINT_BOLD_ALIGN_RIGHT_BLUE.setAlignment(HorizontalAlignment.RIGHT);
        styles.put("PROPORTIONAL_FONT_10_POINT_BOLD_ALIGN_RIGHT_BLUE", PROPORTIONAL_FONT_10_POINT_BOLD_ALIGN_RIGHT_BLUE);

        XSSFCellStyle PROPORTIONAL_FONT_10_POINT_BOLD_ALIGN_CENTER_BLUE = xssfWorkbook.createCellStyle();
        PROPORTIONAL_FONT_10_POINT_BOLD_ALIGN_CENTER_BLUE.cloneStyleFrom(PROPORTIONAL_FONT_10_POINT_BOLD_ALIGN_LEFT_BLUE);
        PROPORTIONAL_FONT_10_POINT_BOLD_ALIGN_CENTER_BLUE.setAlignment(HorizontalAlignment.CENTER);
        styles.put("PROPORTIONAL_FONT_10_POINT_BOLD_ALIGN_CENTER_BLUE", PROPORTIONAL_FONT_10_POINT_BOLD_ALIGN_CENTER_BLUE);

        XSSFCellStyle PROPORTIONAL_FONT_10_POINT_BOLD_ALIGN_RIGHT_YELLOW = xssfWorkbook.createCellStyle();
        PROPORTIONAL_FONT_10_POINT_BOLD_ALIGN_RIGHT_YELLOW.cloneStyleFrom(PROPORTIONAL_FONT_10_POINT_BOLD_ALIGN_LEFT_BLUE);
        PROPORTIONAL_FONT_10_POINT_BOLD_ALIGN_RIGHT_YELLOW.setAlignment(HorizontalAlignment.RIGHT);
        PROPORTIONAL_FONT_10_POINT_BOLD_ALIGN_RIGHT_YELLOW.setFillForegroundColor(WorkbookEnvironment.CELL_BACKGROUND_YELLOW);
        styles.put("PROPORTIONAL_FONT_10_POINT_BOLD_ALIGN_RIGHT_YELLOW", PROPORTIONAL_FONT_10_POINT_BOLD_ALIGN_RIGHT_YELLOW);

        XSSFCellStyle PROPORTIONAL_FONT_10_POINT_BOLD_ALIGN_CENTER_BORDERED = xssfWorkbook.createCellStyle();
        PROPORTIONAL_FONT_10_POINT_BOLD_ALIGN_CENTER_BORDERED.setFont(PROPORTIONAL_FONT_10_POINT_BOLD);
        PROPORTIONAL_FONT_10_POINT_BOLD_ALIGN_CENTER_BORDERED.setVerticalAlignment(VerticalAlignment.CENTER);
        PROPORTIONAL_FONT_10_POINT_BOLD_ALIGN_CENTER_BORDERED.setAlignment(HorizontalAlignment.CENTER);
        PROPORTIONAL_FONT_10_POINT_BOLD_ALIGN_CENTER_BORDERED.setBorderBottom(BorderStyle.THIN);
        PROPORTIONAL_FONT_10_POINT_BOLD_ALIGN_CENTER_BORDERED.setBottomBorderColor(IndexedColors.GREY_50_PERCENT.getIndex());
        PROPORTIONAL_FONT_10_POINT_BOLD_ALIGN_CENTER_BORDERED.setBorderTop(BorderStyle.THIN);
        PROPORTIONAL_FONT_10_POINT_BOLD_ALIGN_CENTER_BORDERED.setTopBorderColor(IndexedColors.GREY_50_PERCENT.getIndex());
        PROPORTIONAL_FONT_10_POINT_BOLD_ALIGN_CENTER_BORDERED.setBorderRight(BorderStyle.THIN);
        PROPORTIONAL_FONT_10_POINT_BOLD_ALIGN_CENTER_BORDERED.setRightBorderColor(IndexedColors.GREY_50_PERCENT.getIndex());
        PROPORTIONAL_FONT_10_POINT_BOLD_ALIGN_CENTER_BORDERED.setBorderLeft(BorderStyle.THIN);
        PROPORTIONAL_FONT_10_POINT_BOLD_ALIGN_CENTER_BORDERED.setLeftBorderColor(IndexedColors.GREY_50_PERCENT.getIndex());
        styles.put("PROPORTIONAL_FONT_10_POINT_BOLD_ALIGN_CENTER_BORDERED", PROPORTIONAL_FONT_10_POINT_BOLD_ALIGN_CENTER_BORDERED);

        XSSFCellStyle PROPORTIONAL_FONT_10_POINT_BOLD_ALIGN_CENTER = xssfWorkbook.createCellStyle();
        PROPORTIONAL_FONT_10_POINT_BOLD_ALIGN_CENTER.setFont(PROPORTIONAL_FONT_10_POINT_BOLD);
        PROPORTIONAL_FONT_10_POINT_BOLD_ALIGN_CENTER.setVerticalAlignment(VerticalAlignment.CENTER);
        PROPORTIONAL_FONT_10_POINT_BOLD_ALIGN_CENTER.setAlignment(HorizontalAlignment.CENTER);
        styles.put("PROPORTIONAL_FONT_10_POINT_BOLD_ALIGN_CENTER", PROPORTIONAL_FONT_10_POINT_BOLD_ALIGN_CENTER);

        XSSFFont PROPORTIONAL_FONT_10_POINT = xssfWorkbook.createFont();
        PROPORTIONAL_FONT_10_POINT.setFontName(WorkbookEnvironment.PROPORTIONAL_FONT_NAME);
        PROPORTIONAL_FONT_10_POINT.setFontHeightInPoints(WorkbookEnvironment.FONT_SIZE_10_POINT);
        PROPORTIONAL_FONT_10_POINT.setBold(false);

        XSSFCellStyle PROPORTIONAL_FONT_10_POINT_ALIGN_LEFT = xssfWorkbook.createCellStyle();
        PROPORTIONAL_FONT_10_POINT_ALIGN_LEFT.setFont(PROPORTIONAL_FONT_10_POINT);
        PROPORTIONAL_FONT_10_POINT_ALIGN_LEFT.setVerticalAlignment(VerticalAlignment.CENTER);
        PROPORTIONAL_FONT_10_POINT_ALIGN_LEFT.setAlignment(HorizontalAlignment.LEFT);
        styles.put("PROPORTIONAL_FONT_10_POINT_ALIGN_LEFT", PROPORTIONAL_FONT_10_POINT_ALIGN_LEFT);

        XSSFFont MONOSPACE_FONT_10_POINT_BOLD = xssfWorkbook.createFont();
        MONOSPACE_FONT_10_POINT_BOLD.setFontName(WorkbookEnvironment.MONOSPACE_FONT_NAME);
        MONOSPACE_FONT_10_POINT_BOLD.setFontHeightInPoints(WorkbookEnvironment.FONT_SIZE_10_POINT);
        MONOSPACE_FONT_10_POINT_BOLD.setBold(true);

        XSSFCellStyle MONOSPACE_FONT_10_POINT_BOLD_ALIGN_RIGHT_BORDERED_DOUBLE_YELLOW = xssfWorkbook.createCellStyle();
        MONOSPACE_FONT_10_POINT_BOLD_ALIGN_RIGHT_BORDERED_DOUBLE_YELLOW.setDataFormat(xssfWorkbook.createDataFormat().getFormat(WorkbookEnvironment.DOUBLE_VALUE_FORMAT));
        MONOSPACE_FONT_10_POINT_BOLD_ALIGN_RIGHT_BORDERED_DOUBLE_YELLOW.setFont(MONOSPACE_FONT_10_POINT_BOLD);
        MONOSPACE_FONT_10_POINT_BOLD_ALIGN_RIGHT_BORDERED_DOUBLE_YELLOW.setAlignment(HorizontalAlignment.RIGHT);
        MONOSPACE_FONT_10_POINT_BOLD_ALIGN_RIGHT_BORDERED_DOUBLE_YELLOW.setVerticalAlignment(VerticalAlignment.CENTER);
        MONOSPACE_FONT_10_POINT_BOLD_ALIGN_RIGHT_BORDERED_DOUBLE_YELLOW.setFillForegroundColor(WorkbookEnvironment.CELL_BACKGROUND_YELLOW);
        MONOSPACE_FONT_10_POINT_BOLD_ALIGN_RIGHT_BORDERED_DOUBLE_YELLOW.setFillPattern(FillPatternType.SOLID_FOREGROUND);
        MONOSPACE_FONT_10_POINT_BOLD_ALIGN_RIGHT_BORDERED_DOUBLE_YELLOW.setBorderBottom(BorderStyle.THIN);
        MONOSPACE_FONT_10_POINT_BOLD_ALIGN_RIGHT_BORDERED_DOUBLE_YELLOW.setBottomBorderColor(IndexedColors.GREY_50_PERCENT.getIndex());
        MONOSPACE_FONT_10_POINT_BOLD_ALIGN_RIGHT_BORDERED_DOUBLE_YELLOW.setBorderTop(BorderStyle.THIN);
        MONOSPACE_FONT_10_POINT_BOLD_ALIGN_RIGHT_BORDERED_DOUBLE_YELLOW.setTopBorderColor(IndexedColors.GREY_50_PERCENT.getIndex());
        MONOSPACE_FONT_10_POINT_BOLD_ALIGN_RIGHT_BORDERED_DOUBLE_YELLOW.setBorderRight(BorderStyle.THIN);
        MONOSPACE_FONT_10_POINT_BOLD_ALIGN_RIGHT_BORDERED_DOUBLE_YELLOW.setRightBorderColor(IndexedColors.GREY_50_PERCENT.getIndex());
        MONOSPACE_FONT_10_POINT_BOLD_ALIGN_RIGHT_BORDERED_DOUBLE_YELLOW.setBorderLeft(BorderStyle.THIN);
        MONOSPACE_FONT_10_POINT_BOLD_ALIGN_RIGHT_BORDERED_DOUBLE_YELLOW.setLeftBorderColor(IndexedColors.GREY_50_PERCENT.getIndex());
        styles.put("MONOSPACE_FONT_10_POINT_BOLD_ALIGN_RIGHT_BORDERED_DOUBLE_YELLOW", MONOSPACE_FONT_10_POINT_BOLD_ALIGN_RIGHT_BORDERED_DOUBLE_YELLOW);

        XSSFCellStyle MONOSPACE_FONT_10_POINT_BOLD_ALIGN_RIGHT_BORDERED_INTEGER_YELLOW = xssfWorkbook.createCellStyle();
        MONOSPACE_FONT_10_POINT_BOLD_ALIGN_RIGHT_BORDERED_INTEGER_YELLOW.cloneStyleFrom(MONOSPACE_FONT_10_POINT_BOLD_ALIGN_RIGHT_BORDERED_DOUBLE_YELLOW);
        MONOSPACE_FONT_10_POINT_BOLD_ALIGN_RIGHT_BORDERED_INTEGER_YELLOW.setDataFormat(xssfWorkbook.createDataFormat().getFormat(WorkbookEnvironment.INTEGER_VALUE_FORMAT));
        styles.put("MONOSPACE_FONT_10_POINT_BOLD_ALIGN_RIGHT_BORDERED_INTEGER_YELLOW", MONOSPACE_FONT_10_POINT_BOLD_ALIGN_RIGHT_BORDERED_INTEGER_YELLOW);

        XSSFCellStyle MONOSPACE_FONT_10_POINT_BOLD_ALIGN_RIGHT_BORDERED_CURRENCY_YELLOW = xssfWorkbook.createCellStyle();
        MONOSPACE_FONT_10_POINT_BOLD_ALIGN_RIGHT_BORDERED_CURRENCY_YELLOW.cloneStyleFrom(MONOSPACE_FONT_10_POINT_BOLD_ALIGN_RIGHT_BORDERED_DOUBLE_YELLOW);
        MONOSPACE_FONT_10_POINT_BOLD_ALIGN_RIGHT_BORDERED_CURRENCY_YELLOW.setDataFormat(xssfWorkbook.createDataFormat().getFormat(WorkbookEnvironment.CURRENCY_VALUE_FORMAT));
        styles.put("MONOSPACE_FONT_10_POINT_BOLD_ALIGN_RIGHT_BORDERED_CURRENCY_YELLOW", MONOSPACE_FONT_10_POINT_BOLD_ALIGN_RIGHT_BORDERED_CURRENCY_YELLOW);

        XSSFCellStyle MONOSPACE_FONT_10_POINT_BOLD_ALIGN_LEFT_YELLOW = xssfWorkbook.createCellStyle();
        MONOSPACE_FONT_10_POINT_BOLD_ALIGN_LEFT_YELLOW.setFont(MONOSPACE_FONT_10_POINT_BOLD);
        MONOSPACE_FONT_10_POINT_BOLD_ALIGN_LEFT_YELLOW.setAlignment(HorizontalAlignment.LEFT);
        MONOSPACE_FONT_10_POINT_BOLD_ALIGN_LEFT_YELLOW.setVerticalAlignment(VerticalAlignment.CENTER);
        MONOSPACE_FONT_10_POINT_BOLD_ALIGN_LEFT_YELLOW.setFillForegroundColor(WorkbookEnvironment.CELL_BACKGROUND_YELLOW);
        MONOSPACE_FONT_10_POINT_BOLD_ALIGN_LEFT_YELLOW.setFillPattern(FillPatternType.SOLID_FOREGROUND);
        styles.put("MONOSPACE_FONT_10_POINT_BOLD_ALIGN_LEFT_YELLOW", MONOSPACE_FONT_10_POINT_BOLD_ALIGN_LEFT_YELLOW);

        XSSFCellStyle MONOSPACE_FONT_10_POINT_BOLD_ALIGN_RIGHT_YELLOW = xssfWorkbook.createCellStyle();
        MONOSPACE_FONT_10_POINT_BOLD_ALIGN_RIGHT_YELLOW.setFont(MONOSPACE_FONT_10_POINT_BOLD);
        MONOSPACE_FONT_10_POINT_BOLD_ALIGN_RIGHT_YELLOW.setAlignment(HorizontalAlignment.RIGHT);
        MONOSPACE_FONT_10_POINT_BOLD_ALIGN_RIGHT_YELLOW.setVerticalAlignment(VerticalAlignment.CENTER);
        MONOSPACE_FONT_10_POINT_BOLD_ALIGN_RIGHT_YELLOW.setFillForegroundColor(WorkbookEnvironment.CELL_BACKGROUND_YELLOW);
        MONOSPACE_FONT_10_POINT_BOLD_ALIGN_RIGHT_YELLOW.setFillPattern(FillPatternType.SOLID_FOREGROUND);
        styles.put("MONOSPACE_FONT_10_POINT_BOLD_ALIGN_RIGHT_YELLOW", MONOSPACE_FONT_10_POINT_BOLD_ALIGN_RIGHT_YELLOW);

        XSSFCellStyle MONOSPACE_FONT_10_POINT_BOLD_ALIGN_LEFT_BORDERED = xssfWorkbook.createCellStyle();
        MONOSPACE_FONT_10_POINT_BOLD_ALIGN_LEFT_BORDERED.setFont(MONOSPACE_FONT_10_POINT_BOLD);
        MONOSPACE_FONT_10_POINT_BOLD_ALIGN_LEFT_BORDERED.setVerticalAlignment(VerticalAlignment.CENTER);
        MONOSPACE_FONT_10_POINT_BOLD_ALIGN_LEFT_BORDERED.setAlignment(HorizontalAlignment.LEFT);
        MONOSPACE_FONT_10_POINT_BOLD_ALIGN_LEFT_BORDERED.setBorderBottom(BorderStyle.THIN);
        MONOSPACE_FONT_10_POINT_BOLD_ALIGN_LEFT_BORDERED.setBottomBorderColor(IndexedColors.GREY_50_PERCENT.getIndex());
        MONOSPACE_FONT_10_POINT_BOLD_ALIGN_LEFT_BORDERED.setBorderTop(BorderStyle.THIN);
        MONOSPACE_FONT_10_POINT_BOLD_ALIGN_LEFT_BORDERED.setTopBorderColor(IndexedColors.GREY_50_PERCENT.getIndex());
        MONOSPACE_FONT_10_POINT_BOLD_ALIGN_LEFT_BORDERED.setBorderRight(BorderStyle.THIN);
        MONOSPACE_FONT_10_POINT_BOLD_ALIGN_LEFT_BORDERED.setRightBorderColor(IndexedColors.GREY_50_PERCENT.getIndex());
        MONOSPACE_FONT_10_POINT_BOLD_ALIGN_LEFT_BORDERED.setBorderLeft(BorderStyle.THIN);
        MONOSPACE_FONT_10_POINT_BOLD_ALIGN_LEFT_BORDERED.setLeftBorderColor(IndexedColors.GREY_50_PERCENT.getIndex());
        styles.put("MONOSPACE_FONT_10_POINT_BOLD_ALIGN_LEFT_BORDERED", MONOSPACE_FONT_10_POINT_BOLD_ALIGN_LEFT_BORDERED);

        XSSFCellStyle MONOSPACE_FONT_10_POINT_BOLD_ALIGN_RIGHT_BORDERED_DOUBLE = xssfWorkbook.createCellStyle();
        MONOSPACE_FONT_10_POINT_BOLD_ALIGN_RIGHT_BORDERED_DOUBLE.cloneStyleFrom(MONOSPACE_FONT_10_POINT_BOLD_ALIGN_LEFT_BORDERED);
        MONOSPACE_FONT_10_POINT_BOLD_ALIGN_RIGHT_BORDERED_DOUBLE.setDataFormat(xssfWorkbook.createDataFormat().getFormat(WorkbookEnvironment.DOUBLE_VALUE_FORMAT));
        styles.put("MONOSPACE_FONT_10_POINT_BOLD_ALIGN_RIGHT_BORDERED_DOUBLE", MONOSPACE_FONT_10_POINT_BOLD_ALIGN_RIGHT_BORDERED_DOUBLE);

        XSSFCellStyle MONOSPACE_FONT_10_POINT_BOLD_ALIGN_RIGHT_BORDERED_INTEGER = xssfWorkbook.createCellStyle();
        MONOSPACE_FONT_10_POINT_BOLD_ALIGN_RIGHT_BORDERED_INTEGER.cloneStyleFrom(MONOSPACE_FONT_10_POINT_BOLD_ALIGN_LEFT_BORDERED);
        MONOSPACE_FONT_10_POINT_BOLD_ALIGN_RIGHT_BORDERED_INTEGER.setDataFormat(xssfWorkbook.createDataFormat().getFormat(WorkbookEnvironment.INTEGER_VALUE_FORMAT));
        styles.put("MONOSPACE_FONT_10_POINT_BOLD_ALIGN_RIGHT_BORDERED_INTEGER", MONOSPACE_FONT_10_POINT_BOLD_ALIGN_RIGHT_BORDERED_INTEGER);

        XSSFCellStyle MONOSPACE_FONT_10_POINT_BOLD_ALIGN_RIGHT_BORDERED_CURRENCY = xssfWorkbook.createCellStyle();
        MONOSPACE_FONT_10_POINT_BOLD_ALIGN_RIGHT_BORDERED_CURRENCY.cloneStyleFrom(MONOSPACE_FONT_10_POINT_BOLD_ALIGN_LEFT_BORDERED);
        MONOSPACE_FONT_10_POINT_BOLD_ALIGN_RIGHT_BORDERED_CURRENCY.setDataFormat(xssfWorkbook.createDataFormat().getFormat(WorkbookEnvironment.CURRENCY_VALUE_FORMAT));
        styles.put("MONOSPACE_FONT_10_POINT_BOLD_ALIGN_RIGHT_BORDERED_CURRENCY", MONOSPACE_FONT_10_POINT_BOLD_ALIGN_RIGHT_BORDERED_CURRENCY);

        XSSFFont MONOSPACE_FONT_10_POINT = xssfWorkbook.createFont();
        MONOSPACE_FONT_10_POINT.setFontName(WorkbookEnvironment.MONOSPACE_FONT_NAME);
        MONOSPACE_FONT_10_POINT.setFontHeightInPoints(WorkbookEnvironment.FONT_SIZE_10_POINT);
        MONOSPACE_FONT_10_POINT.setBold(false);

        XSSFCellStyle MONOSPACE_FONT_10_POINT_ALIGN_LEFT_BORDERED = xssfWorkbook.createCellStyle();
        MONOSPACE_FONT_10_POINT_ALIGN_LEFT_BORDERED.setFont(MONOSPACE_FONT_10_POINT);
        MONOSPACE_FONT_10_POINT_ALIGN_LEFT_BORDERED.setVerticalAlignment(VerticalAlignment.CENTER);
        MONOSPACE_FONT_10_POINT_ALIGN_LEFT_BORDERED.setAlignment(HorizontalAlignment.LEFT);
        MONOSPACE_FONT_10_POINT_ALIGN_LEFT_BORDERED.setBorderBottom(BorderStyle.THIN);
        MONOSPACE_FONT_10_POINT_ALIGN_LEFT_BORDERED.setBottomBorderColor(IndexedColors.GREY_50_PERCENT.getIndex());
        MONOSPACE_FONT_10_POINT_ALIGN_LEFT_BORDERED.setBorderTop(BorderStyle.THIN);
        MONOSPACE_FONT_10_POINT_ALIGN_LEFT_BORDERED.setTopBorderColor(IndexedColors.GREY_50_PERCENT.getIndex());
        MONOSPACE_FONT_10_POINT_ALIGN_LEFT_BORDERED.setBorderRight(BorderStyle.THIN);
        MONOSPACE_FONT_10_POINT_ALIGN_LEFT_BORDERED.setRightBorderColor(IndexedColors.GREY_50_PERCENT.getIndex());
        MONOSPACE_FONT_10_POINT_ALIGN_LEFT_BORDERED.setBorderLeft(BorderStyle.THIN);
        MONOSPACE_FONT_10_POINT_ALIGN_LEFT_BORDERED.setLeftBorderColor(IndexedColors.GREY_50_PERCENT.getIndex());
        styles.put("MONOSPACE_FONT_10_POINT_ALIGN_LEFT_BORDERED", MONOSPACE_FONT_10_POINT_ALIGN_LEFT_BORDERED);

        XSSFCellStyle MONOSPACE_FONT_10_POINT_ALIGN_RIGHT_BORDERED = xssfWorkbook.createCellStyle();
        MONOSPACE_FONT_10_POINT_ALIGN_RIGHT_BORDERED.cloneStyleFrom(MONOSPACE_FONT_10_POINT_ALIGN_LEFT_BORDERED);
        MONOSPACE_FONT_10_POINT_ALIGN_RIGHT_BORDERED.setAlignment(HorizontalAlignment.RIGHT);
        styles.put("MONOSPACE_FONT_10_POINT_ALIGN_RIGHT_BORDERED", MONOSPACE_FONT_10_POINT_ALIGN_RIGHT_BORDERED);

        XSSFCellStyle MONOSPACE_FONT_10_POINT_ALIGN_CENTER_BORDERED = xssfWorkbook.createCellStyle();
        MONOSPACE_FONT_10_POINT_ALIGN_CENTER_BORDERED.cloneStyleFrom(MONOSPACE_FONT_10_POINT_ALIGN_LEFT_BORDERED);
        MONOSPACE_FONT_10_POINT_ALIGN_CENTER_BORDERED.setAlignment(HorizontalAlignment.CENTER);
        styles.put("MONOSPACE_FONT_10_POINT_ALIGN_CENTER_BORDERED", MONOSPACE_FONT_10_POINT_ALIGN_CENTER_BORDERED);

        XSSFCellStyle MONOSPACE_FONT_10_POINT_ALIGN_RIGHT_BORDERED_DOUBLE = xssfWorkbook.createCellStyle();
        MONOSPACE_FONT_10_POINT_ALIGN_RIGHT_BORDERED_DOUBLE.cloneStyleFrom(MONOSPACE_FONT_10_POINT_ALIGN_LEFT_BORDERED);
        MONOSPACE_FONT_10_POINT_ALIGN_RIGHT_BORDERED_DOUBLE.setDataFormat(xssfWorkbook.createDataFormat().getFormat(WorkbookEnvironment.DOUBLE_VALUE_FORMAT));
        styles.put("MONOSPACE_FONT_10_POINT_ALIGN_RIGHT_BORDERED_DOUBLE", MONOSPACE_FONT_10_POINT_ALIGN_RIGHT_BORDERED_DOUBLE);

        XSSFCellStyle MONOSPACE_FONT_10_POINT_ALIGN_RIGHT_BORDERED_INTEGER = xssfWorkbook.createCellStyle();
        MONOSPACE_FONT_10_POINT_ALIGN_RIGHT_BORDERED_INTEGER.cloneStyleFrom(MONOSPACE_FONT_10_POINT_ALIGN_LEFT_BORDERED);
        MONOSPACE_FONT_10_POINT_ALIGN_RIGHT_BORDERED_INTEGER.setDataFormat(xssfWorkbook.createDataFormat().getFormat(WorkbookEnvironment.INTEGER_VALUE_FORMAT));
        styles.put("MONOSPACE_FONT_10_POINT_ALIGN_RIGHT_BORDERED_INTEGER", MONOSPACE_FONT_10_POINT_ALIGN_RIGHT_BORDERED_INTEGER);

        XSSFCellStyle MONOSPACE_FONT_10_POINT_ALIGN_RIGHT_BORDERED_CURRENCY = xssfWorkbook.createCellStyle();
        MONOSPACE_FONT_10_POINT_ALIGN_RIGHT_BORDERED_CURRENCY.cloneStyleFrom(MONOSPACE_FONT_10_POINT_ALIGN_LEFT_BORDERED);
        MONOSPACE_FONT_10_POINT_ALIGN_RIGHT_BORDERED_CURRENCY.setDataFormat(xssfWorkbook.createDataFormat().getFormat(WorkbookEnvironment.CURRENCY_VALUE_FORMAT));
        styles.put("MONOSPACE_FONT_10_POINT_ALIGN_RIGHT_BORDERED_CURRENCY", MONOSPACE_FONT_10_POINT_ALIGN_RIGHT_BORDERED_CURRENCY);

        XSSFCellStyle MONOSPACE_FONT_10_POINT_ALIGN_RIGHT_BORDERED_PRICE = xssfWorkbook.createCellStyle();
        MONOSPACE_FONT_10_POINT_ALIGN_RIGHT_BORDERED_PRICE.cloneStyleFrom(MONOSPACE_FONT_10_POINT_ALIGN_LEFT_BORDERED);
        MONOSPACE_FONT_10_POINT_ALIGN_RIGHT_BORDERED_PRICE.setDataFormat(xssfWorkbook.createDataFormat().getFormat(WorkbookEnvironment.CUSTOM_PRICE_FORMAT));
        styles.put("MONOSPACE_FONT_10_POINT_ALIGN_RIGHT_BORDERED_PRICE", MONOSPACE_FONT_10_POINT_ALIGN_RIGHT_BORDERED_PRICE);

        XSSFCellStyle MONOSPACE_FONT_10_POINT_ALIGN_RIGHT_BORDERED_PRICE_PROMOTION = xssfWorkbook.createCellStyle();
        MONOSPACE_FONT_10_POINT_ALIGN_RIGHT_BORDERED_PRICE_PROMOTION.cloneStyleFrom(MONOSPACE_FONT_10_POINT_ALIGN_RIGHT_BORDERED_PRICE);
        MONOSPACE_FONT_10_POINT_ALIGN_RIGHT_BORDERED_PRICE_PROMOTION.setFillForegroundColor(WorkbookEnvironment.CELL_BACKGROUND_GREEN);
        MONOSPACE_FONT_10_POINT_ALIGN_RIGHT_BORDERED_PRICE_PROMOTION.setFillPattern(FillPatternType.SOLID_FOREGROUND);
        styles.put("MONOSPACE_FONT_10_POINT_ALIGN_RIGHT_BORDERED_PRICE_PROMOTION", MONOSPACE_FONT_10_POINT_ALIGN_RIGHT_BORDERED_PRICE_PROMOTION);

        XSSFFont MONOSPACE_FONT_12_POINT_BOLD = xssfWorkbook.createFont();
        MONOSPACE_FONT_12_POINT_BOLD.setFontName(WorkbookEnvironment.MONOSPACE_FONT_NAME);
        MONOSPACE_FONT_12_POINT_BOLD.setFontHeightInPoints(WorkbookEnvironment.FONT_SIZE_12_POINT);
        MONOSPACE_FONT_12_POINT_BOLD.setBold(true);

        XSSFCellStyle MONOSPACE_FONT_12_POINT_BOLD_ALIGN_RIGHT_BORDERED_DOUBLE = xssfWorkbook.createCellStyle();
        MONOSPACE_FONT_12_POINT_BOLD_ALIGN_RIGHT_BORDERED_DOUBLE.setFont(MONOSPACE_FONT_12_POINT_BOLD);
        MONOSPACE_FONT_12_POINT_BOLD_ALIGN_RIGHT_BORDERED_DOUBLE.setDataFormat(xssfWorkbook.createDataFormat().getFormat(WorkbookEnvironment.DOUBLE_VALUE_FORMAT));
        MONOSPACE_FONT_12_POINT_BOLD_ALIGN_RIGHT_BORDERED_DOUBLE.setBorderBottom(BorderStyle.THIN);
        MONOSPACE_FONT_12_POINT_BOLD_ALIGN_RIGHT_BORDERED_DOUBLE.setBottomBorderColor(IndexedColors.GREY_50_PERCENT.getIndex());
        MONOSPACE_FONT_12_POINT_BOLD_ALIGN_RIGHT_BORDERED_DOUBLE.setBorderTop(BorderStyle.THIN);
        MONOSPACE_FONT_12_POINT_BOLD_ALIGN_RIGHT_BORDERED_DOUBLE.setTopBorderColor(IndexedColors.GREY_50_PERCENT.getIndex());
        MONOSPACE_FONT_12_POINT_BOLD_ALIGN_RIGHT_BORDERED_DOUBLE.setBorderRight(BorderStyle.THIN);
        MONOSPACE_FONT_12_POINT_BOLD_ALIGN_RIGHT_BORDERED_DOUBLE.setRightBorderColor(IndexedColors.GREY_50_PERCENT.getIndex());
        MONOSPACE_FONT_12_POINT_BOLD_ALIGN_RIGHT_BORDERED_DOUBLE.setBorderLeft(BorderStyle.THIN);
        MONOSPACE_FONT_12_POINT_BOLD_ALIGN_RIGHT_BORDERED_DOUBLE.setLeftBorderColor(IndexedColors.GREY_50_PERCENT.getIndex());
        styles.put("MONOSPACE_FONT_12_POINT_BOLD_ALIGN_RIGHT_BORDERED_DOUBLE", MONOSPACE_FONT_12_POINT_BOLD_ALIGN_RIGHT_BORDERED_DOUBLE);

        XSSFCellStyle MONOSPACE_FONT_12_POINT_BOLD_ALIGN_RIGHT_BORDERED_INTEGER = xssfWorkbook.createCellStyle();
        MONOSPACE_FONT_12_POINT_BOLD_ALIGN_RIGHT_BORDERED_INTEGER.cloneStyleFrom(MONOSPACE_FONT_12_POINT_BOLD_ALIGN_RIGHT_BORDERED_DOUBLE);
        MONOSPACE_FONT_12_POINT_BOLD_ALIGN_RIGHT_BORDERED_INTEGER.setDataFormat(xssfWorkbook.createDataFormat().getFormat(WorkbookEnvironment.INTEGER_VALUE_FORMAT));
        styles.put("MONOSPACE_FONT_12_POINT_BOLD_ALIGN_RIGHT_BORDERED_INTEGER", MONOSPACE_FONT_12_POINT_BOLD_ALIGN_RIGHT_BORDERED_INTEGER);

        XSSFCellStyle MONOSPACE_FONT_12_POINT_BOLD_ALIGN_RIGHT_BORDERED_CURRENCY = xssfWorkbook.createCellStyle();
        MONOSPACE_FONT_12_POINT_BOLD_ALIGN_RIGHT_BORDERED_CURRENCY.cloneStyleFrom(MONOSPACE_FONT_12_POINT_BOLD_ALIGN_RIGHT_BORDERED_DOUBLE);
        MONOSPACE_FONT_12_POINT_BOLD_ALIGN_RIGHT_BORDERED_CURRENCY.setDataFormat(xssfWorkbook.createDataFormat().getFormat(WorkbookEnvironment.CURRENCY_VALUE_FORMAT));
        styles.put("MONOSPACE_FONT_12_POINT_BOLD_ALIGN_RIGHT_BORDERED_CURRENCY", MONOSPACE_FONT_12_POINT_BOLD_ALIGN_RIGHT_BORDERED_CURRENCY);
    }
}
